[package]
name = "dioxus_bulma"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.1", features = ["web"] }
dioxus-logger = "0.5.1"
dioxus-web = "0.5.1"
log = "0.4.21"
tracing = "0.1.40"
tracing-wasm = "0.2.1"
